# Generated by Django 5.1.4 on 2024-12-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blog_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
