# Generated by Django 5.1.4 on 2024-12-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_college_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='link',
            field=models.URLField(default='https://example.com'),
        ),
    ]
