# Generated by Django 5.1.4 on 2024-12-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_college_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='link',
        ),
        migrations.AddField(
            model_name='college',
            name='Link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
